apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sample-java-deployment
  labels:
    app: sample-java-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        apps: java-app-container
    spec:
      containers:
      - name: java-app-container
        image: 810877976727.dkr.ecr.us-east-1.amazonaws.com/javarepo:latest
        ports:
        - containerPort: 8081 
